sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5t7P4izqNLPo9RYM4qEF
    access-key-secret: IFUbEzo9zhRy0GAXkNPXUYMgC1mdOn
    bucket-name: koen